spring:
  application:
    name: auth-service

server:
  port: 9001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost